--- #YAML:1.0
name:               lib
version:            0.63
abstract:           manipulate @INC at compile time
author:
    - Steffen Mueller <smueller@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
provides:
    lib:
        file:     lib_pm.PL
        version:  0.63
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
